// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApplication2.Models
{
    [Table("Category")]
    public partial class Category
    {
        public Category()
        {
            SubCategories = new HashSet<SubCategory>();
        }

        [Key]
        [Column("categoryID")]
        public byte CategoryId { get; set; }
        [Column("categoryName")]
        [StringLength(30)]
        [Unicode(false)]
        public string CategoryName { get; set; }

        [InverseProperty("Category")]
        public virtual ICollection<SubCategory> SubCategories { get; set; }
    }
}