// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApplication2.Models
{
    [Table("Course")]
    public partial class Course
    {
        public Course()
        {
            Reviews = new HashSet<Review>();
        }

        [Key]
        [Column("courseID")]
        public int CourseId { get; set; }
        [Column("courseDescription")]
        [StringLength(10)]
        public string CourseDescription { get; set; }
        [Column("topicsCovered")]
        [StringLength(10)]
        public string TopicsCovered { get; set; }
        [Column("categoryID")]
        public byte? CategoryId { get; set; }
        [Column("subcategoryID")]
        public int? SubcategoryId { get; set; }
        [Column("platform")]
        [StringLength(30)]
        [Unicode(false)]
        public string Platform { get; set; }
        [Column("languageID")]
        public int? LanguageId { get; set; }
        [Column("level")]
        public byte? Level { get; set; }
        [Column("priceStatus")]
        public bool? PriceStatus { get; set; }
        [Column("lastUpdate", TypeName = "date")]
        public DateTime? LastUpdate { get; set; }
        [Column("addingDate", TypeName = "date")]
        public DateTime? AddingDate { get; set; }
        [Column("picture")]
        [StringLength(50)]
        public string Picture { get; set; }
        [Column("averageRating")]
        public int? AverageRating { get; set; }
        [Column("status")]
        public bool? Status { get; set; }
        [Column("instructorID")]
        public int? InstructorId { get; set; }
        [Column("instructorFullName")]
        [StringLength(50)]
        public string InstructorFullName { get; set; }
        [Column("vedioLenght")]
        [StringLength(10)]
        public string VedioLenght { get; set; }
        [Column("courseDuration")]
        [StringLength(10)]
        [Unicode(false)]
        public string CourseDuration { get; set; }
        [Column("link")]
        [Unicode(false)]
        public string Link { get; set; }

        [ForeignKey("InstructorId")]
        [InverseProperty("Courses")]
        public virtual User Instructor { get; set; }
        [ForeignKey("LanguageId")]
        [InverseProperty("Courses")]
        public virtual Language Language { get; set; }
        [ForeignKey("SubcategoryId")]
        [InverseProperty("Courses")]
        public virtual SubCategory Subcategory { get; set; }
        [InverseProperty("Course")]
        public virtual ICollection<Review> Reviews { get; set; }
    }
}