// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication2.Models
{
    public partial class Course
    {
        public Course()
        {
            Reviews = new HashSet<Review>();
        }

        public string AddedByUserId { get; set; }
        public int CourseId { get; set; }
        public string CourseDescription { get; set; }
        public string TopicsCovered { get; set; }
        public byte? CategoryId { get; set; }
        public int? SubcategoryId { get; set; }
        public string Platform { get; set; }
        public int? LanguageId { get; set; }
        public byte? Level { get; set; }
        public bool? PriceStatus { get; set; }
        public DateTime? LastUpdate { get; set; }
        public DateTime? AddingDate { get; set; }
        public string Picture { get; set; }
        public int? AverageRating { get; set; }
        public bool? Claimed { get; set; }
        public bool? Status { get; set; }
        public string InstructorId { get; set; }
        public string InstructorFullName { get; set; }
        public string VedioLenght { get; set; }
        public string CourseDuration { get; set; }
        public string Link { get; set; }

        public virtual User AddedByUser { get; set; }
        public virtual Instructor Instructor { get; set; }
        public virtual Language Language { get; set; }
        public virtual SubCategory Subcategory { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }
    }
}