// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics.Metrics;
using WebApplication2.Helpers;
using WebApplication2.Helpers.Enums;

namespace WebApplication2.Models
{
    public partial class Course
    {
        public Course()
        {
            Reviews = new HashSet<Review>();
        }

        public string? Title { get; set; }
        public string AddedByUserId { get; set; }//= Guid.NewGuid().ToString();
        public int CourseId { get; set; }
        public string? CourseDescription { get; set; }
        public string? TopicsCovered { get; set; }
        public byte? CategoryId { get; set; }
        public int? SubcategoryId { get; set; }
        public string? Platform { get; set; }
        public int? LanguageId { get; set; }

        [Required]
        public Level? Level { get; set; }
        public  bool? PriceStatus { get; set; }
        public DateTime? LastUpdate { get; set; }
        public DateTime AddingDate { get; set; }= DateTime.Now;
        public string? Picture { get; set; }
        public double? AverageRating { get; set; } = 0.0;
        public bool? Claimed { get; set; }
        public bool Status { get; set; }
        public string? InstructorId { get; set; }
        public string? InstructorFullName { get; set; }
       // [Required]
        public VideoLengthCategory? VedioLength { get; set; }
        public int? CourseDuration { get; set; }
        public string? Link { get; set; }

        public double? AverageMaterialQuality { get; set; } = 0.0;
        public double? AverageSupportQuality {  get; set; }= 0.0;
        public double? AverageEngagementLevel { get; set; } = 0.0;
        public double? AverageTechnicalQuality { get; set; } = 0.0;
        public double? AverageContentQuality { get; set; } = 0.0;
        public double? AverageOverallSatisfaction { get; set; } = 0.0;


        public virtual User AddedByUser { get; set; }
        public virtual Instructor Instructor { get; set; }
        public virtual Language Language { get; set; }
        public virtual SubCategory Subcategory { get; set; }
        public virtual ICollection<Review> Reviews { get; set; } 
    }
}