// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApplication2.Models
{
    [Table("Instructor")]
    public partial class Instructor
    {
        public Instructor()
        {
            SocialMediaAccounts = new HashSet<SocialMediaAccount>();
        }

        [Key]
        [Column("instructorID")]
        public int InstructorId { get; set; }
        [Column("countryCode")]
        public int CountryCode { get; set; }
        [Column("phoneNumber")]
        public int PhoneNumber { get; set; }
        [Column("profession")]
        [StringLength(50)]
        [Unicode(false)]
        public string Profession { get; set; }
        [Column("yearsExperince")]
        public byte? YearsExperince { get; set; }
        [Required]
        [Column("about")]
        [StringLength(10)]
        public string About { get; set; }
        [Column("status")]
        public bool? Status { get; set; }

        [ForeignKey("InstructorId")]
        [InverseProperty("Instructor")]
        public virtual User InstructorNavigation { get; set; }
        [InverseProperty("Instructor")]
        public virtual ICollection<SocialMediaAccount> SocialMediaAccounts { get; set; }
    }
}