// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication2.Models
{
    public partial class Instructor
    {
        public Instructor()
        {
            Courses = new HashSet<Course>();
            SocialMediaAccounts = new HashSet<SocialMediaAccount>();
        }

        public string InstructorId { get; set; }
        public string CountryCode { get; set; }
        public string Profession { get; set; }
        public byte? YearsExperince { get; set; }
        public string About { get; set; }

        public virtual User InstructorNavigation { get; set; }
        public virtual ICollection<Course> Courses { get; set; }
        public virtual ICollection<SocialMediaAccount> SocialMediaAccounts { get; set; }
    }
}