// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApplication2.Models
{
    [Table("Language")]
    public partial class Language
    {
        public Language()
        {
            Courses = new HashSet<Course>();
        }

        [Key]
        [Column("languageID")]
        public int LanguageId { get; set; }
        [Required]
        [Column("name")]
        [StringLength(50)]
        [Unicode(false)]
        public string Name { get; set; }

        [InverseProperty("Language")]
        public virtual ICollection<Course> Courses { get; set; }
    }
}