// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApplication2.Models
{
    [Table("Report")]
    public partial class Report
    {
        [Key]
        [Column("reportID")]
        public int ReportId { get; set; }
        [Column("message")]
        public string Message { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime ReportDate { get; set; }
        [Column("reviewID")]
        public int? ReviewId { get; set; }
        [Column("status")]
        public bool Status { get; set; }
        [Column("studentID")]
        public int StudentId { get; set; }

        [ForeignKey("ReviewId")]
        [InverseProperty("Reports")]
        public virtual Review Review { get; set; }
        [ForeignKey("StudentId")]
        [InverseProperty("Reports")]
        public virtual Student Student { get; set; }
    }
}