// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication2.Models
{
    public partial class Report
    {
        public int ReportId { get; set; }
        public string Message { get; set; }
        public DateTime ReportDate { get; set; } = DateTime.Now;
        public int ReviewId { get; set; }
        public bool Status { get; set; }
        public string StudentId { get; set; }

        public virtual Review Review { get; set; }
        public virtual Student Student { get; set; }
    }
}