// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApplication2.Models
{
    [Table("Review")]
    public partial class Review
    {
        public Review()
        {
            Reports = new HashSet<Report>();
        }

        [Key]
        [Column("reviewID")]
        public int ReviewId { get; set; }
        [StringLength(10)]
        public string Descritipn { get; set; }
        [Column("rate")]
        public byte? Rate { get; set; }
        [Column("ratingDate", TypeName = "datetime")]
        public DateTime? RatingDate { get; set; }
        [Column("courseID")]
        public int CourseId { get; set; }
        [Column("studentID")]
        public int StudentId { get; set; }

        [ForeignKey("CourseId")]
        [InverseProperty("Reviews")]
        public virtual Course Course { get; set; }
        [ForeignKey("StudentId")]
        [InverseProperty("Reviews")]
        public virtual Student Student { get; set; }
        [InverseProperty("Review")]
        public virtual ICollection<Report> Reports { get; set; }
    }
}