// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication2.Models
{
    public partial class Review
    {
        public Review()
        {
            Reports = new HashSet<Report>();
        }

        public int ReviewId { get; set; }
        public string Descritipn { get; set; }
        public bool? Status { get; set; }
        public byte? Rate { get; set; }
        public DateTime? RatingDate { get; set; }
        public int? CourseId { get; set; }
        public string StudentId { get; set; }
         
        public virtual Course Course { get; set; }
        public virtual Student Student { get; set; }

        public virtual ICollection<Report> Reports { get; set; }
    }
}