// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication2.Models
{
    public partial class SocialMediaAccount
    {
        public int AccountId { get; set; }
        public string Account { get; set; }
        public string InstructorId { get; set; }

        public virtual Instructor Instructor { get; set; }
    }
}