// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApplication2.Models
{
    [Table("SocialMediaAccount")]
    public partial class SocialMediaAccount
    {
        [Key]
        [Column("accountID")]
        public int AccountId { get; set; }
        [Column("account")]
        [StringLength(50)]
        [Unicode(false)]
        public string Account { get; set; }
        [Column("instructorID")]
        public int InstructorId { get; set; }

        [ForeignKey("InstructorId")]
        [InverseProperty("SocialMediaAccounts")]
        public virtual Instructor Instructor { get; set; }
    }
}