// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApplication2.Models
{
    [Table("Student")]
    public partial class Student
    {
        public Student()
        {
            Reports = new HashSet<Report>();
            Reviews = new HashSet<Review>();
            UserInterests = new HashSet<UserInterest>();
        }

        [Key]
        [Column("studentID")]
        public int StudentId { get; set; }
        [Column("contributionNum")]
        public byte? ContributionNum { get; set; }

        [ForeignKey("StudentId")]
        [InverseProperty("Student")]
        public virtual User StudentNavigation { get; set; }
        [InverseProperty("Student")]
        public virtual ICollection<Report> Reports { get; set; }
        [InverseProperty("Student")]
        public virtual ICollection<Review> Reviews { get; set; }
        [InverseProperty("Student")]
        public virtual ICollection<UserInterest> UserInterests { get; set; }
    }
}