// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication2.Models
{
    public partial class Student
    {
        public Student()
        {
            Reports = new HashSet<Report>();
            Reviews = new HashSet<Review>();
            Subs = new HashSet<SubCategory>();
        }

        public string StudentId { get; set; }
        public byte? ContributionNum { get; set; }

        public virtual User StudentNavigation { get; set; }
        public virtual ICollection<Report> Reports { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }

        public virtual ICollection<SubCategory> Subs { get; set; }
    }
}