// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication2.Models
{
    public partial class SubCategory
    {
        public SubCategory()
        {
            Courses = new HashSet<Course>();
            Students = new HashSet<Student>();
        }

        public int SubId { get; set; }
        public string SubName { get; set; }
        public byte CategoryId { get; set; }

        public virtual Category Category { get; set; }
        public virtual ICollection<Course> Courses { get; set; }

        public virtual ICollection<Student> Students { get; set; }
    }
}