// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApplication2.Models
{
    [Table("SubCategory")]
    public partial class SubCategory
    {
        public SubCategory()
        {
            Courses = new HashSet<Course>();
        }

        [Key]
        [Column("subID")]
        public int SubId { get; set; }
        [Column("subName")]
        [StringLength(30)]
        [Unicode(false)]
        public string SubName { get; set; }
        [Column("categoryID")]
        public byte CategoryId { get; set; }

        [ForeignKey("CategoryId")]
        [InverseProperty("SubCategories")]
        public virtual Category Category { get; set; }
        [InverseProperty("Subcategory")]
        public virtual ICollection<Course> Courses { get; set; }
    }
}