// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApplication2.Models
{
    [Table("User")]
    public partial class User
    {
        public User()
        {
            Courses = new HashSet<Course>();
        }

        [Key]
        [Column("userID")]
        public int UserId { get; set; }
        [Required]
        [Column("firstName")]
        [StringLength(50)]
        [Unicode(false)]
        public string FirstName { get; set; }
        [Required]
        [Column("lastName")]
        [StringLength(20)]
        [Unicode(false)]
        public string LastName { get; set; }
        [Required]
        [Column("email")]
        [StringLength(30)]
        [Unicode(false)]
        public string Email { get; set; }
        [Required]
        [Column("password")]
        [StringLength(50)]
        public string Password { get; set; }
        [Column("pic")]
        [StringLength(50)]
        public string Pic { get; set; }
        [Column("registerDate", TypeName = "date")]
        public DateTime? RegisterDate { get; set; }
        [Column("userType")]
        public byte UserType { get; set; }

        [InverseProperty("InstructorNavigation")]
        public virtual Instructor Instructor { get; set; }
        [InverseProperty("StudentNavigation")]
        public virtual Student Student { get; set; }
        [InverseProperty("Instructor")]
        public virtual ICollection<Course> Courses { get; set; }
    }
}