// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;

namespace WebApplication2.Models
{
    public partial class User:IdentityUser
    {
        public User()
        {
            Courses = new HashSet<Course>();
        }

        
        public string FirstName { get; set; }
        public string LastName { get; set; }
       
        public string Pic { get; set; }
        public DateTime? RegisterDate { get; set; }=DateTime.Now;
        public bool? Status { get; set; }
       

        public virtual Instructor Instructor { get; set; }
        public virtual Student Student { get; set; }
        public virtual ICollection<Course> Courses { get; set; }
    }
}