// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApplication2.Models
{
    public partial class UserInterest
    {
        [Key]
        [Column("studentID")]
        public int StudentId { get; set; }
        [Key]
        [Column("subID")]
        public int SubId { get; set; }

        [ForeignKey("StudentId")]
        [InverseProperty("UserInterests")]
        public virtual Student Student { get; set; }
    }
}